openapi: 3.0.1
info:
  title: Connect
  description: API Definition of Connect
  version: 1.0.0
servers:
- url: http://localhost:8290/connect
paths:
  /:
    get:
      responses:
        default:
          description: Default response
